name = "OurPkg"
uuid = "da339061-3b1d-43e9-84fa-463e9c6eba1e"
authors = ["Lucas C Wilcox <lucas@swirlee.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
